remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - etl_pipeline.md

title: Health Informatics ETL Pipeline Project
description: This website showcases the development of our ETL pipeline.